config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/distribucion_agencia'
  get 'dashboard/distribucion_estado'
  get 'dashboard/promedio_espera'
  get 'dashboard/promedio_atencion'
  get 'dashboard/send_report'

  devise_for :usuarios
  get 'home/index'

  resources :atendidos #se crea

  resources :agencias
  resources :atenciones do
    member do
      get 'atendido'
    end
  end
  resources :turnos
  resources :usuarios
  resources :recepciones do #agregamos
    member do
      get 'atender'
    end
  end

  root 'home#index'
  

end

app/controllers/atenciones_controller.rb
class AtencionesController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_atencion, only: [:atendido, :show, :edit, :update, :destroy]

  # GET /atenciones
  # GET /atenciones.json
  def index
    @atenciones = Atencion.all
  end

  # GET /atenciones/1
  # GET /atenciones/1.json
  def show
  end

  def atendido
    @atencion.to_atendido
    redirect_to recepciones_path
  end

  # GET /atenciones/new
  def new
    @atencion = Atencion.new
  end

  # GET /atenciones/1/edit
  def edit
  end

  # POST /atenciones
  # POST /atenciones.json
  def create
    @atencion = Atencion.new(atencion_params)

    respond_to do |format|
      if @atencion.save
        format.html { redirect_to @atencion, notice: 'Atencion was successfully created.' }
        format.json { render :show, status: :created, location: @atencion }
      else
        format.html { render :new }
        format.json { render json: @atencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atenciones/1
  # PATCH/PUT /atenciones/1.json
  def update
    respond_to do |format|
      if @atencion.update(atencion_params)
        format.html { redirect_to @atencion, notice: 'Atencion was successfully updated.' }
        format.json { render :show, status: :ok, location: @atencion }
      else
        format.html { render :edit }
        format.json { render json: @atencion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atenciones/1
  # DELETE /atenciones/1.json
  def destroy
    @atencion.destroy
    respond_to do |format|
      format.html { redirect_to atenciones_url, notice: 'Atencion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atencion
      @atencion = Atencion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atencion_params
      params.require(:atencion).permit(:descripcion, :comentario)
    end
end

app/helpers/atenciones_helper.rb
module AtencionesHelper
end

app/views/atenciones/_form.html.erb
<%= form_for(@atencion) do |f| %>
  <% if @atencion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atencion.errors.count, "error") %> prohibited this atencion from being saved:</h2>

      <ul>
      <% @atencion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_area :comentario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atenciones/edit.html.erb
<h1>Editing Atencion</h1>

<%= render 'form' %>

<%= link_to 'Show', @atencion %> |
<%= link_to 'Back', atenciones_path %>

app/views/atenciones/index.html.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Tiempo de atencion</th>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Comentario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atenciones.each do |atencion| %>
      <tr>
        <td><%= distance_of_time_in_words_to_now(atencion.hora_atencion)%></td>
        <td><%= atencion.nombres %></td>
        <td><%= atencion.descripcion %></td>
        <td><%= atencion.comentario %></td>
        <td><%= link_to 'ver', atencion %></td>
        <td><%= link_to 'Editar', edit_atencion_path(atencion) %></td>
       </tr>
    <% end %>
  </tbody>
</table>

app/views/atenciones/new.html.erb
<h1>New Atencion</h1>

<%= render 'form' %>

<%= link_to 'Back', atenciones_path %>

app/views/atenciones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @atencion.descripcion %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @atencion.comentario %>
</p>

<%= link_to 'Edit', edit_atencion_path(@atencion) %> |
<%= link_to 'Back', atenciones_path %>
<%= link_to 'Atendido', atendido_atencion_path(@atencion) %>