config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/distribucion_agencia'
  get 'dashboard/distribucion_estado'
  get 'dashboard/promedio_espera'
  get 'dashboard/promedio_atencion'
  get 'dashboard/send_report'

  devise_for :usuarios
  get 'home/index'

  resources :atendidos #se crea

  resources :agencias
  resources :atenciones do
    member do
      get 'atendido'
    end
  end
  resources :turnos
  resources :usuarios
  resources :recepciones do #agregamos
    member do
      get 'atender'
    end
  end

  root 'home#index'
  

end

app/views/shared/_busqueda.html.erb
 <%= search_form_for @q do |f| %>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Busqueda</h4>
      </div>
      <div class="modal-body">
        <% campos_busqueda.each do |campo| %>
          <%= f.label campo %>
          <%= f.search_field campo, class: 'form-control' %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= f.submit 'Buscar', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_header.html.erb
<div class = "header">
		<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png', class: 'img-responsive'), root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if usuario_signed_in? %> <!-- para que no muestre el menu -->
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to 'Recepcion', new_recepcion_path %> </li>
        <li><%= link_to 'Sala de espera', recepciones_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administracion <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Agencias', agencias_path %></li>
            <li><%= link_to 'Usuarios', usuarios_path %></li>
            <li><%= link_to 'Turnos', turnos_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Estadisticas de atención', dashboard_path %></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <% end %>
     <ul class="nav navbar-nav navbar-right">
      <% if usuario_signed_in? %> <!-- agregamos -->
         <li> <!-- agregamos -->
            <p class="navbar-text"> <!-- agregamos -->
              <%= current_usuario.nombre %> <!-- agregamos -->
            </p> <!-- agregamos -->
         </li>


         <li class="dropdown"> 
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Perfil', usuario_path(current_usuario) %></li>
            <li role="separator" class="divider"></li>
              <li><%= link_to 'Salir', destroy_usuario_session_path, method: :delete %></li> <!-- agregamos -->
          </ul>
        </li>
        <% else %> <!-- agregamos -->
        <li> <%= link_to 'Ingresar', new_usuario_session_path %></li> <!-- agregamos -->
        <% end %> <!-- agregamos -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


	</div>

app/views/shared/header.pdf.erb
<%= wicked_pdf_image_tag 'imagen.png'%>