config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/distribucion_agencia'
  get 'dashboard/distribucion_estado'
  get 'dashboard/promedio_espera'
  get 'dashboard/promedio_atencion'
  get 'dashboard/send_report'

  devise_for :usuarios
  get 'home/index'

  resources :atendidos #se crea

  resources :agencias
  resources :atenciones do
    member do
      get 'atendido'
    end
  end
  resources :turnos
  resources :usuarios
  resources :recepciones do #agregamos
    member do
      get 'atender'
    end
  end

  root 'home#index'
  

end

app/models/agencia.rb
class Agencia < ActiveRecord::Base

	include Export

	enum zona: {centro: 'centro', uraba: 'uraba', costa: 'costa', choco: 'choco'}
end

app/controllers/agencias_controller.rb
class AgenciasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_agencia, only: [:show, :edit, :update, :destroy]

  # GET /agencias
  # GET /agencias.json
  def index
   @q = Agencia.ransack(params[:q])
    @agencias = @q.result

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Listado de agencias'
      end
      format.csv do
        send_data @agencias.to_csv
      end
    end
  end

  # GET /agencias/1
  # GET /agencias/1.json
  def show
  end

  # GET /agencias/new
  def new
    @agencia = Agencia.new
  end

  # GET /agencias/1/edit
  def edit
  end

  # POST /agencias
  # POST /agencias.json
  def create
    @agencia = Agencia.new(agencia_params)

    respond_to do |format|
      if @agencia.save
        format.html { redirect_to @agencia, notice: 'Agencia was successfully created.' }
        format.json { render :show, status: :created, location: @agencia }
      else
        format.html { render :new }
        format.json { render json: @agencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencias/1
  # PATCH/PUT /agencias/1.json
  def update
    respond_to do |format|
      if @agencia.update(agencia_params)
        format.html { redirect_to @agencia, notice: 'Agencia was successfully updated.' }
        format.json { render :show, status: :ok, location: @agencia }
      else
        format.html { render :edit }
        format.json { render json: @agencia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencias/1
  # DELETE /agencias/1.json
  def destroy
    @agencia.destroy
    respond_to do |format|
      format.html { redirect_to agencias_url, notice: 'Agencia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agencia
      @agencia = Agencia.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agencia_params
      params.require(:agencia).permit(:nombre, :direccion, :telefono, :zona, :numero)
    end
end

app/helpers/agencias_helper.rb
module AgenciasHelper
end

app/views/agencias/_form.html.erb
<%= form_for(@agencia) do |f| %>
  <% if @agencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agencia.errors.count, "error") %> prohibited this agencia from being saved:</h2>

      <ul>
      <% @agencia.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

  <div class="col-md-6">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono, class: 'form-control'  %>
  </div>
  <div class="col-md-6">
    <%= f.label :zona %><br>
    <%= f.collection_select :zona, Agencia.zonas, :first, :first, {}, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :numero %><br>
    <%= f.number_field :numero, class: 'form-control'  %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <br>
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
</div>  
<% end %>

app/views/agencias/edit.html.erb
<h1>Editing Agencia</h1>

<%= render 'form' %>

<%= link_to 'Show', @agencia %> |
<%= link_to 'Back', agencias_path %>

app/views/agencias/index.html.erb
<div class="row">
  <div class="col-md-6 col-sm-6">
    <h3>Listado de Agencias</h3>
  </div>
  <div class="col-md-6 col-sm-6">
    <div class="btn-group pull-right">
      <%= link_to 'Buscar', '#', class: 'btn btn-default', data: {target: '#myModal', toggle: 'modal'} %>

      <div class="btn-group">
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" >
            Descargar
            <span class="caret"></span>
          </button>

            <ul class="dropdown-menu">
              <li><%=link_to 'PDF', agencias_path(format: :pdf) %></li>
              <li><%=link_to 'CSV', agencias_path(format: :csv) %></li>
            </ul> 
        </div>   
      </div>
    </div>
  </div>
</div> 


<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Zona</th>
      <th>Numero</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencias.each do |agencia| %>
      <tr>
        <td><%= agencia.nombre %></td>
        <td><%= agencia.direccion %></td>
        <td><%= agencia.telefono %></td>
        <td><%= agencia.zona %></td>
        <td><%= agencia.numero %></td>
        <td><%= link_to 'Show', agencia, class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_agencia_path(agencia), class: 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', agencia, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agencia', new_agencia_path, class: 'btn btn-primary' %>

<%= render partial: 'shared/busqueda', locals: { campos_busqueda: 
                                                    [
                                                     :nombre_cont,
                                                     :direccion_cont, 
                                                     :telefono_cont,
                                                     :numero_eq
                                                     ] 
                                                }
%>

app/views/agencias/index.pdf.erb
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Zona</th>
      <th>Numero</th>
    </tr>
  </thead>

  <tbody>
    <% @agencias.each do |agencia| %>
      <tr>
        <td><%= agencia.nombre %></td>
        <td><%= agencia.direccion %></td>
        <td><%= agencia.telefono %></td>
        <td><%= agencia.zona %></td>
        <td><%= agencia.numero %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/agencias/new.html.erb
<h1>New Agencia</h1>

<%= render 'form' %>

<%= link_to 'Back', agencias_path %>

app/views/agencias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @agencia.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @agencia.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @agencia.telefono %>
</p>

<p>
  <strong>Zona:</strong>
  <%= @agencia.zona %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @agencia.numero %>
</p>

<%= link_to 'Edit', edit_agencia_path(@agencia) %> |
<%= link_to 'Back', agencias_path %>