config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'

  get 'dashboard', to: 'dashboard#index'
  get 'dashboard/distribucion_agencia'
  get 'dashboard/distribucion_estado'
  get 'dashboard/promedio_espera'
  get 'dashboard/promedio_atencion'
  get 'dashboard/send_report'

  devise_for :usuarios
  get 'home/index'

  resources :atendidos #se crea

  resources :agencias
  resources :atenciones do
    member do
      get 'atendido'
    end
  end
  resources :turnos
  resources :usuarios
  resources :recepciones do #agregamos
    member do
      get 'atender'
    end
  end

  root 'home#index'
  

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #esto lo inserto al momento de ejecutar el comando rails g devise usuario
         :recoverable, :rememberable, :trackable, :validatable
	enum estado: [:inactivo, :activo] #agregamos
	enum rol: [:admin, :operativo, :gerente] #agregamos

	#has_secure_password     #para encriptar el pasword

	belongs_to :agencia 
	
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
     respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Listado de turnos'
      end
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
     u_params = params.require(:usuario).permit(:nombre, :apellido, :agencia_id, :rol, :estado, :codigo, :email, :login, :cedula, :password, :password_confirmation)
     u_params.delete(:password) if u_params[:password].blank?
     u_params.delete(:password_confirmation) if u_params[:password_confirmation].blank?
     u_params
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

  <div class="col-md-6">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :agencia %><br>
    <%= f.collection_select :agencia_id, Agencia.all.sort_by(&:nombre), :id, :nombre, {prompt: 'Seleccione una agencia'}, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :rol %><br>
    <%= f.collection_select :rol, Usuario.roles, :first, :first, {}, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :estado %><br>
    <%= f.collection_select :estado, Usuario.estados, :first, :first, {}, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :codigo %><br>
    <%= f.text_field :codigo, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :login %><br>
    <%= f.text_field :login, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :password %><br>
    <%= f.text_field :password, class: 'form-control' %>
  </div>
  <div class="col-md-6">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation, class: 'form-control' %>
  </div>
</div>

 <div class="row">
  <div class="col-md-6">
    <br>
    <%= f.submit 'Guardar', class: 'btn btn-primary' %>
  </div>
</div> 
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Agencia</th>
      <th>Rol</th>
      <th>Estado</th>
      <th>Codigo</th>
      <th>Correo</th>
      <th>Login</th>
      <th>Cedula</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.agencia.try(:nombre) %></td>
        <td><%= usuario.rol %></td>
        <td><%= usuario.estado %></td>
        <td><%= usuario.codigo %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.login %></td>
        <td><%= usuario.cedula %></td>
        <div class="btn-group">
        <td>
        <%= link_to 'Show', usuario, class: 'btn btn-default btn-xs' %>
        <%= link_to 'Edit', edit_usuario_path(usuario), class: 'btn btn-default btn-xs' %>
        <%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
        </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path, class: 'btn btn-primary' %>

app/views/usuarios/index.pdf.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Agencia</th>
      <th>Rol</th>
      <th>Estado</th>
      <th>Codigo</th>
      <th>Correo</th>
      <th>Login</th>
      <th>Cedula</th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.agencia.try(:nombre) %></td>
        <td><%= usuario.rol %></td>
        <td><%= usuario.estado %></td>
        <td><%= usuario.codigo %></td>
        <td><%= usuario.email %></td>
        <td><%= usuario.login %></td>
        <td><%= usuario.cedula %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        Imágen de perfil
      </div>
      <div class="panel-body"></div>
    </div>
  </div>  
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Detalles de la cuenta
      </div>
      <table class="table">
        <tr>
          <td><b>Nombre: </b> <%= @usuario.nombre %></td>
          <td><b>Apellido: </b> <%= @usuario.apellido %></td>
        </tr>
         <tr>
          <td><b>Agencia: </b> <%= @usuario.agencia.try(:nombre) %></td>
          <td><b>Rol: </b> <%= @usuario.rol %></td>
        </tr>
        <tr>
          <td><b>Estado: </b> <%= @usuario.estado %></td>
          <td><b>Codigo: </b> <%= @usuario.codigo %></td>
        </tr>
        <tr>
          <td><b>Email: </b> <%= @usuario.email %></td>
          <td><b>Login: </b> <%= @usuario.login %></td>
        </tr>
        <tr>
          <td><b>Cedula: </b> <%= @usuario.cedula %></td>
          <td></td>
        </tr>
      </table>
    </div>
  </div>
</div>



<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>